server:
  http:
    network: "tcp"
    addr: "0.0.0.0:8000"
    timeout: 10s
  grpc:
    network: "tcp"
    addr: "0.0.0.0:9000"
    timeout: 10s

data:
  database:
    driver: "postgres"
    source: "host=localhost port=5432 user=blog password=blog dbname=blog sslmode=disable"

auth:
  jwt_secret: "change-me-in-prod"
  expire: 24h
