// Code generated by hand to match protoc-gen-go output structure.
package v1

type CreateCommentRequest struct {
	PostId  int64  `json:"post_id,omitempty"`
	Content string `json:"content,omitempty"`
}

func (m *CreateCommentRequest) GetPostId() int64   { if m != nil { return m.PostId }; return 0 }
func (m *CreateCommentRequest) GetContent() string { if m != nil { return m.Content }; return "" }

func (m *CreateCommentRequest) Validate() error {
	if err := validateInt64Gt("post_id", m.PostId, 0); err != nil {
		return err
	}
	if err := validateStrLen("content", m.Content, 1, 2000); err != nil {
		return err
	}
	return nil
}

type ListCommentRequest struct {
	PostId int64 `json:"post_id,omitempty"`
	Page   int32 `json:"page,omitempty"`
	Size   int32 `json:"size,omitempty"`
}

func (m *ListCommentRequest) GetPostId() int64 { if m != nil { return m.PostId }; return 0 }
func (m *ListCommentRequest) GetPage() int32   { if m != nil { return m.Page }; return 0 }
func (m *ListCommentRequest) GetSize() int32   { if m != nil { return m.Size }; return 0 }

func (m *ListCommentRequest) Validate() error {
	if err := validateInt64Gt("post_id", m.PostId, 0); err != nil {
		return err
	}
	if err := validateInt32Range("page", m.Page, 0, 1<<30); err != nil {
		return err
	}
	if err := validateInt32Range("size", m.Size, 0, 100); err != nil {
		return err
	}
	return nil
}

type ListCommentReply struct {
	Comments []*CommentInfo `json:"comments,omitempty"`
	Total    int64          `json:"total,omitempty"`
	Page     int32          `json:"page,omitempty"`
	Size     int32          `json:"size,omitempty"`
}

func (m *ListCommentReply) GetComments() []*CommentInfo { if m != nil { return m.Comments }; return nil }
func (m *ListCommentReply) GetTotal() int64             { if m != nil { return m.Total }; return 0 }
func (m *ListCommentReply) GetPage() int32              { if m != nil { return m.Page }; return 0 }
func (m *ListCommentReply) GetSize() int32              { if m != nil { return m.Size }; return 0 }

type CommentInfo struct {
	Id             int64  `json:"id,omitempty"`
	PostId         int64  `json:"post_id,omitempty"`
	AuthorId       int64  `json:"author_id,omitempty"`
	AuthorNickname string `json:"author_nickname,omitempty"`
	Content        string `json:"content,omitempty"`
	CreatedAt      string `json:"created_at,omitempty"`
}

func (m *CommentInfo) GetId() int64              { if m != nil { return m.Id }; return 0 }
func (m *CommentInfo) GetPostId() int64          { if m != nil { return m.PostId }; return 0 }
func (m *CommentInfo) GetAuthorId() int64        { if m != nil { return m.AuthorId }; return 0 }
func (m *CommentInfo) GetAuthorNickname() string { if m != nil { return m.AuthorNickname }; return "" }
func (m *CommentInfo) GetContent() string        { if m != nil { return m.Content }; return "" }
func (m *CommentInfo) GetCreatedAt() string      { if m != nil { return m.CreatedAt }; return "" }

type LikeRequest struct {
	PostId int64 `json:"post_id,omitempty"`
}

func (m *LikeRequest) GetPostId() int64 { if m != nil { return m.PostId }; return 0 }

func (m *LikeRequest) Validate() error {
	return validateInt64Gt("post_id", m.PostId, 0)
}

type LikeReply struct {
	LikesCount int64 `json:"likes_count,omitempty"`
	Liked      bool  `json:"liked,omitempty"`
}

func (m *LikeReply) GetLikesCount() int64 { if m != nil { return m.LikesCount }; return 0 }
func (m *LikeReply) GetLiked() bool       { if m != nil { return m.Liked }; return false }
