// Code generated by hand to match protoc-gen-go output structure.
package v1

type CreatePostRequest struct {
	Title        string   `json:"title,omitempty"`
	BodyMarkdown string   `json:"body_markdown,omitempty"`
	Tags         []string `json:"tags,omitempty"`
}

func (m *CreatePostRequest) GetTitle() string         { if m != nil { return m.Title }; return "" }
func (m *CreatePostRequest) GetBodyMarkdown() string  { if m != nil { return m.BodyMarkdown }; return "" }
func (m *CreatePostRequest) GetTags() []string        { if m != nil { return m.Tags }; return nil }

func (m *CreatePostRequest) Validate() error {
	if err := validateStrLen("title", m.Title, 1, 200); err != nil {
		return err
	}
	if err := validateStrLen("body_markdown", m.BodyMarkdown, 1, 100000); err != nil {
		return err
	}
	if err := validateTags("tags", m.Tags, 10, 1, 32); err != nil {
		return err
	}
	return nil
}

type GetPostRequest struct {
	Id int64 `json:"id,omitempty"`
}

func (m *GetPostRequest) GetId() int64 { if m != nil { return m.Id }; return 0 }

func (m *GetPostRequest) Validate() error {
	return validateInt64Gt("id", m.Id, 0)
}

type ListPostRequest struct {
	Page int32  `json:"page,omitempty"`
	Size int32  `json:"size,omitempty"`
	Tag  string `json:"tag,omitempty"`
}

func (m *ListPostRequest) GetPage() int32  { if m != nil { return m.Page }; return 0 }
func (m *ListPostRequest) GetSize() int32  { if m != nil { return m.Size }; return 0 }
func (m *ListPostRequest) GetTag() string  { if m != nil { return m.Tag }; return "" }

func (m *ListPostRequest) Validate() error {
	if err := validateInt32Range("page", m.Page, 0, 1<<30); err != nil {
		return err
	}
	if err := validateInt32Range("size", m.Size, 0, 100); err != nil {
		return err
	}
	if err := validateStrLen("tag", m.Tag, 0, 32); err != nil {
		return err
	}
	return nil
}

type ListPostReply struct {
	Posts []*PostInfo `json:"posts,omitempty"`
	Total int64       `json:"total,omitempty"`
	Page  int32       `json:"page,omitempty"`
	Size  int32       `json:"size,omitempty"`
}

func (m *ListPostReply) GetPosts() []*PostInfo { if m != nil { return m.Posts }; return nil }
func (m *ListPostReply) GetTotal() int64       { if m != nil { return m.Total }; return 0 }
func (m *ListPostReply) GetPage() int32        { if m != nil { return m.Page }; return 0 }
func (m *ListPostReply) GetSize() int32        { if m != nil { return m.Size }; return 0 }

type UpdatePostRequest struct {
	Id           int64    `json:"id,omitempty"`
	Title        string   `json:"title,omitempty"`
	BodyMarkdown string   `json:"body_markdown,omitempty"`
	Tags         []string `json:"tags,omitempty"`
}

func (m *UpdatePostRequest) GetId() int64            { if m != nil { return m.Id }; return 0 }
func (m *UpdatePostRequest) GetTitle() string        { if m != nil { return m.Title }; return "" }
func (m *UpdatePostRequest) GetBodyMarkdown() string { if m != nil { return m.BodyMarkdown }; return "" }
func (m *UpdatePostRequest) GetTags() []string       { if m != nil { return m.Tags }; return nil }

func (m *UpdatePostRequest) Validate() error {
	if err := validateInt64Gt("id", m.Id, 0); err != nil {
		return err
	}
	if err := validateStrLen("title", m.Title, 1, 200); err != nil {
		return err
	}
	if err := validateStrLen("body_markdown", m.BodyMarkdown, 1, 100000); err != nil {
		return err
	}
	if err := validateTags("tags", m.Tags, 10, 1, 32); err != nil {
		return err
	}
	return nil
}

type DeletePostRequest struct {
	Id int64 `json:"id,omitempty"`
}

func (m *DeletePostRequest) GetId() int64 { if m != nil { return m.Id }; return 0 }

func (m *DeletePostRequest) Validate() error {
	return validateInt64Gt("id", m.Id, 0)
}

type DeletePostReply struct {
	Ok bool `json:"ok,omitempty"`
}

func (m *DeletePostReply) GetOk() bool { if m != nil { return m.Ok }; return false }

type PostInfo struct {
	Id             int64    `json:"id,omitempty"`
	AuthorId       int64    `json:"author_id,omitempty"`
	AuthorNickname string   `json:"author_nickname,omitempty"`
	Title          string   `json:"title,omitempty"`
	BodyMarkdown   string   `json:"body_markdown,omitempty"`
	Tags           []string `json:"tags,omitempty"`
	LikesCount     int64    `json:"likes_count,omitempty"`
	CreatedAt      string   `json:"created_at,omitempty"`
	UpdatedAt      string   `json:"updated_at,omitempty"`
}

func (m *PostInfo) GetId() int64              { if m != nil { return m.Id }; return 0 }
func (m *PostInfo) GetAuthorId() int64        { if m != nil { return m.AuthorId }; return 0 }
func (m *PostInfo) GetAuthorNickname() string { if m != nil { return m.AuthorNickname }; return "" }
func (m *PostInfo) GetTitle() string          { if m != nil { return m.Title }; return "" }
func (m *PostInfo) GetBodyMarkdown() string   { if m != nil { return m.BodyMarkdown }; return "" }
func (m *PostInfo) GetTags() []string         { if m != nil { return m.Tags }; return nil }
func (m *PostInfo) GetLikesCount() int64      { if m != nil { return m.LikesCount }; return 0 }
func (m *PostInfo) GetCreatedAt() string      { if m != nil { return m.CreatedAt }; return "" }
func (m *PostInfo) GetUpdatedAt() string      { if m != nil { return m.UpdatedAt }; return "" }
