// Code generated by hand to match protoc-gen-go output structure.
// Regenerate with `make api` (requires buf + protoc-gen-go) to replace.

package v1

import "time"

// --- User messages ---

type RegisterRequest struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
	Nickname string `json:"nickname,omitempty"`
}

func (m *RegisterRequest) GetEmail() string    { if m != nil { return m.Email }; return "" }
func (m *RegisterRequest) GetPassword() string { if m != nil { return m.Password }; return "" }
func (m *RegisterRequest) GetNickname() string { if m != nil { return m.Nickname }; return "" }

// Validate 基于 proto validate 规则的最小校验（min/max_len、email 形式）
func (m *RegisterRequest) Validate() error {
	if err := validateEmail("email", m.Email, 128); err != nil {
		return err
	}
	if err := validateStrLen("password", m.Password, 8, 64); err != nil {
		return err
	}
	if err := validateStrLen("nickname", m.Nickname, 1, 32); err != nil {
		return err
	}
	return nil
}

type RegisterReply struct {
	Id        int64  `json:"id,omitempty"`
	Email     string `json:"email,omitempty"`
	Nickname  string `json:"nickname,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}

func (m *RegisterReply) GetId() int64         { if m != nil { return m.Id }; return 0 }
func (m *RegisterReply) GetEmail() string     { if m != nil { return m.Email }; return "" }
func (m *RegisterReply) GetNickname() string  { if m != nil { return m.Nickname }; return "" }
func (m *RegisterReply) GetCreatedAt() string { if m != nil { return m.CreatedAt }; return "" }

type LoginRequest struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}

func (m *LoginRequest) GetEmail() string    { if m != nil { return m.Email }; return "" }
func (m *LoginRequest) GetPassword() string { if m != nil { return m.Password }; return "" }

func (m *LoginRequest) Validate() error {
	if err := validateEmail("email", m.Email, 128); err != nil {
		return err
	}
	if err := validateStrLen("password", m.Password, 8, 64); err != nil {
		return err
	}
	return nil
}

type LoginReply struct {
	Token     string    `json:"token,omitempty"`
	ExpiresIn int64     `json:"expires_in,omitempty"`
	User      *UserInfo `json:"user,omitempty"`
}

func (m *LoginReply) GetToken() string     { if m != nil { return m.Token }; return "" }
func (m *LoginReply) GetExpiresIn() int64  { if m != nil { return m.ExpiresIn }; return 0 }
func (m *LoginReply) GetUser() *UserInfo   { if m != nil { return m.User }; return nil }

type GetMeRequest struct{}

func (m *GetMeRequest) Validate() error { return nil }

type UserInfo struct {
	Id        int64  `json:"id,omitempty"`
	Email     string `json:"email,omitempty"`
	Nickname  string `json:"nickname,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}

func (m *UserInfo) GetId() int64         { if m != nil { return m.Id }; return 0 }
func (m *UserInfo) GetEmail() string     { if m != nil { return m.Email }; return "" }
func (m *UserInfo) GetNickname() string  { if m != nil { return m.Nickname }; return "" }
func (m *UserInfo) GetCreatedAt() string { if m != nil { return m.CreatedAt }; return "" }

// 便捷：time.Time → RFC3339
func FormatTime(t time.Time) string {
	return t.UTC().Format(time.RFC3339)
}
